/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "primary": "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1b1b1b",
        "on-primary-container": "#848484",
        "secondary": "#5d5f5f",
        "on-secondary": "#ffffff",
        "secondary-container": "#dfe0e0",
        "on-secondary-container": "#616363",
        "tertiary": "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#1b1c1c",
        "on-tertiary-container": "#848484",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "background": "#f9f9f9",
        "on-background": "#1b1b1b",
        "surface": "#f9f9f9",
        "on-surface": "#1b1b1b",
        "surface-variant": "#e2e2e2",
        "on-surface-variant": "#4c4546",
        "surface-container": "#eeeeee",
        "surface-container-low": "#f3f3f3",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f9f9f9",
        "surface-dim": "#dadada",
        "surface-tint": "#5e5e5e",
        "outline": "#7e7576",
        "outline-variant": "#cfc4c5",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f1f1f1",
        "inverse-primary": "#c6c6c6",
      },
      spacing: {
        "xs": 8,
        "sm": 16,
        "md": 24,
        "lg": 40,
        "xl": 64,
        "gutter": 16,
        "margin-mobile": 16,
        "margin-desktop": 32,
      },
    },
  },
  plugins: [],
};
